### ISSUE TITLE
public repo checklist

### ISSUE THREAD

**Issue by thepwagner** [Shopify/hansel#8]
TODO before making the repo public:

- [x] coding standards: reviewed with _amcleodca - the integration test is weird but acceptable
- [x] CLA probot configured
- [x] Documentation
    - [x] `README.md`
    - [x] add a cool demo.gif https://github.com/Shopify/hansel/pull/9
    - [x] `CONTRIBUTING.md` #6 
    - [x] Code of Conduct (via https://github.com/Shopify/.github/blob/main/CODE_OF_CONDUCT.md)
    - [x] `LICENSE.md`
- [x] verify examples https://github.com/Shopify/hansel/issues/7
- [x] delete comments from internal bots
- [x] make public
- [ ] 🍨
